== Glossary

[glossary]

AGG::
    The http://antigrain.com[Anti-Grain Graphics library] used by default for bitmap (PNG, JPEG, ...) output.
    
Cairo:: 
CairoGraphics::
    The http://cairographics.org[Cairo Graphics library] used for vector format output (SVG, PDF, PS) output by default, and also for bitmap output when esplicitly requested.

Compositing::
    Compositing provides different ways to combine data to be drawn with already existing from drawing previous layers.

GDAL::
    https://gdal.org/[GDAL] is a library for processing various raster and vector geospatial data formats released by the https://www.osgeo.org/[Open Source Geospatial Foundation] (OSGeo). The vector format support also runs under the name OGR for historical reasons.

GPS::
    Global Positioning System

GPX::
    GPS exchange format - an XML format to represent GPS data.

Harfbuzz::
    https://harfbuzz.github.io/[Harfbuzz] is a Text rendering / shaping library used by Mapnik starting with V3.0

Imposm::
    https://imposm.org/[Imposm] is a toll to import OpenStreetMap data into a PostGIS database. (See also: Osm2pgsql)

MapOSMatic::
    A web frontend and render backend to generate printable map posters and booklets using Mapnik, Python and Cairo Graphics

Opacity::
    Defines how opaque or transparent a feature should be. Values range from 0.0 for total transparency to 1.0 for total opacity.

OGR:: 
    The vector format related part of GDAL.
    
OSGeo::
    The https://www.osgeo.org/[Open Source Geospatial Foundation]
    
Osm2pgsql::
    https://osm2pgsql.org/[Osm2pgsql] is a tool to import OpenStreetMap data into a PostGIS database. It is part of the tool chain used to generated the map tiles provided on https://openstreetmap.org[`openstreetmap.org`. (see also: Imposm)
    
PBF::
    Protocol Buffer Format - a file format for OSM data based on the https://developers.google.com/protocol-buffers[Google ProtoBuf library]. PBF is a binary format not suitable for human readning, but very compact, with file sizes typically only almost half of bzip2 compressed OSM XML. 
    
Symbolizer::
	A symbolizer describes how features appear on rendered maps.
	
SVG Transformations::
    SVG transformations allow to translate, scale, rotate or skew a shape, either by combining one or more individual operations, or by giving them as a transformation matrix right away.

