:sourcedir: ../../..

==== PointSymbolizer

The point symbolizer draws a given image at a point position. When given a line or polygon as input the shape will be put at the middle of the line or center of the polygon. 

If no image file is specified a small square is used as the default point image.

For putting symbols along a line or the edge of a polygon the MarkerSymbolizer is usually a better choice.

.PointSymbolizer Attributes
[width="100%",options="header,unbreakable",cols="m,d,d,d"]
|====================
| Attribute          | Type          | Default | Description
| <<example-pointsymbolizer-file,file>>             | file path     | none |
| base             | string | none | name of a <FileSource> to find the input file in
| allow-overlap    | bool          | false 
| <<example-pointsymbolizer-opacity,opacity>>          | float         | 1.0 |
| <<example-pointsymbolizer-placement,placement>> | string | cetroid | Wehter to place on a polygons centroid, which can actually be outside, or its interior
| ignore-placement | bool          | false |  
| transform        | SVG transform | identity |
| comp-op          | Compositing   | src-over |

|====================



.PointSymbolizer file
[#example-pointsymbolizer-file]
====
[source,xml]
-----
include::{sourcedir}/examples/PointSymbolizer-file.xml[]
-----
image::examples/PointSymbolizer-file.svg[align="center"]
====

.PointSymbolizer opacity
[#example-pointsymbolizer-opacity]
====
[source,xml]
-----
include::{sourcedir}/examples/PointSymbolizer-opacity.xml[]
-----
image::examples/PointSymbolizer-opacity.svg[align="center"]
====

.PointSymbolizer placement
[#example-pointsymbolizer-placement]
====
[source,xml]
-----
include::{sourcedir}/examples/PointSymbolizer-placement.xml[]
-----
image::examples/PointSymbolizer-placement.svg[align="center"]
====

.PointSymbolizer scaling 
[#example-pointsymbolizer-scaling]
====
[source,xml]
-----
include::{sourcedir}/examples/PointSymbolizer-transform-scale.xml[]
-----
image::examples/PointSymbolizer-transform-scale.svg[align="center"]
====

.PointSymbolizer rotation
[#example-pointsymbolizer-rotation]
====
[source,xml]
-----
include::{sourcedir}/examples/PointSymbolizer-transform-rotate.xml[]
-----
image::examples/PointSymbolizer-transform-rotate.svg[align="center"]
====

.PointSymbolizer compositing
====
TODO
====
