:sourcedir: ../../..

==== TextSymbolizer

.TextSymbolizer specific Attributes
[width="100%",options="header,unbreakable",cols="m,d,d,d"]
|====================
| Attribute             | Type          | Default  | Description
| face-name             | string        | none     | Face name to use
| fontset-name          | string        | none     | FontSet name
| size                  | float         | 10.0     | Font size in pixels
| fill                  | color         | black    | Text fill color
| character-spacing     | float         | 0.0      | Additional space between characters in pixels
| line-spacing          | float         | 0.0      | Extra vertical space for multi line output in pixels
| opacity               | float         | 1.0      | Text opacity
| font-feature-settings | string        | none     | Comma separated list of https://drafts.csswg.org/css-fonts-3/#propdef-font-feature-settings[OpenType typographic features]
| halo-fill             | color         | white    | Text halo color
| halo-opacity          | float         | 1.0      | Text halo opacity
| halo-radius           | float         | 0.0      | Text halo radius in pixels
| halo-rasterizer       | full, fast    | full     | Text halo rasterizing algorithm when using Agg renderer
| halo-comp-op          | string        | src-over | Compositing operator to use for the halo
| spacing               | integer       | 0        | Spacing between text labels on lines if > 0 (in pixels?)
| placement             | string        | point    | One of `point`, `line`, `vertex`, `interior`, `grid`, `alternating-grid`
| placement-type        | string        | dummy    | Algorithm to use to avoid text overlaps, one of `dummy`, `simple`, `list`
| placements            | string        | none     | If "placement-type" is set to "simple", use this "POSITIONS,[SIZES]" string. An example is text-placements: "E,NE,SE,W,NW,SW" (TODO: better explanation)
|====================

.TextSymbolizer size
====
[source,xml]
-----
include::{sourcedir}/examples/TextSymbolizer-size.xml[]
-----
image::examples/TextSymbolizer-size.svg[align="center"]
====

.TextSymbolizer text color fill
====
[source,xml]
-----
include::{sourcedir}/examples/TextSymbolizer-fill.xml[]
-----
image::examples/TextSymbolizer-fill.svg[align="center"]
====

.TextSymbolizer character spacing
====
[source,xml]
-----
include::{sourcedir}/examples/TextSymbolizer-character-spacing.xml[]
-----
image::examples/TextSymbolizer-character-spacing.svg[align="center"]
====

.TextSymbolizer spacing
====
[source,xml]
-----
include::{sourcedir}/examples/TextSymbolizer-spacing.xml[]
-----
image::examples/TextSymbolizer-spacing.svg[align="center"]
====

.TextSymbolizer placement
====
`placement` Controls where the text is actually placed:

`point`:: Places the text just once at the center of the geometry. In case of a polygon that may actually be outside of the polygon surface, depending on its shape

`interior`:: Similar to `point`, but makes sure that the text is placed inside a polygon even if its center point is actually on its outside

`line`:: When `spacing` is larger than zero the text is repeatedly printed along a line or a polygons outline with `spacing` pixels between texts

`vertex`:: Tries to place the text on each vertex point of a line or a polygons outline

`grid`:: When `grid-cell-width` and `grid-cell-height` are greater than zero the text is repeatedly printed into a polygons surface, using grid cells of the given width and height. Note that the text is not clipped at the border of the polygon, so some text may be printed slightly outside of the polygon surface.

`alternating-grid`:: Similar to `grid`, but each second row is horizontally displaced by half of `grid-cell-width`
[source,xml]
-----
include::{sourcedir}/examples/TextSymbolizer-placement.xml[]
-----
image::examples/TextSymbolizer-placement.svg[align="center"]
====

.TextSymbolizer grid width/height
====
[source,xml]
-----
include::{sourcedir}/examples/TextSymbolizer-grid-width-height.xml[]
-----
image::examples/TextSymbolizer-grid-width-height.svg[align="center"]
====

.TextSymbolizer minimum path length
====
[source,xml]
-----
include::{sourcedir}/examples/TextSymbolizer-minimum-path-length.xml[]
-----
image::examples/TextSymbolizer-minimum-path-length.svg[align="center"]
====

